---
title: "QuickTest"
format: html
editor: visual
---

# Set up

## Libraries

```{r}
library(tidyverse)
library(fastcmprsk)
```

## Source Functions

```{r}
source("../R/cv_ssl_psdh.r")
source("../R/fit_ssl_psdh.r")
source("../R/update_betas.r")
source("../R/expected_inclusion_probs.r")
source("../R/expected_penalty_weights.r")
source("../R/update_mixture_prob.r")
source("../R/helpers.r")
source("../R/tune_ssl_psdh.r")
source("../R/measure_ssl_psdh.r")
source("../R/predict_from_ssl_psdh.r")
source("../R/generate_foldid.r")
```

## Load Data

```{r}
df_asv <- read_csv("~/Documents/ODSi/ODSiData/AnalyticCohort/Example_Data/df_asv.csv")
df_genus<- read_csv("~/Documents/ODSi/ODSiData/AnalyticCohort/Example_Data/df_genus.csv")
df_asv_key<- read_csv("~/Documents/ODSi/ODSiData/AnalyticCohort/Example_Data/df_asv_key.csv")
df_genus_key<- read_csv("~/Documents/ODSi/ODSiData/AnalyticCohort/Example_Data/df_genus_key.csv")
```

# Hypotheses

-   Protective taxa

    -   Blautia

    -   Clostridiales

-   Deleterious taxa

    -   Enterococcus

    -   Lactobacillales

# Running Model

## Function

```{r}

test_run <- function(studyname, df, df_key){
temp_x <- df %>%
  filter(study == studyname)%>%
  select(starts_with("ASV"))

temp_y <- df %>%
  filter(study == studyname)%>%
  select(TTE, GVHD_STATUS)

temp_initialize <- fit_ssl_psdh(as.matrix(temp_x),
             as.matrix(temp_y),
                   ss=c(0.01, 0.5),
                   initial_sparsity = 0.05,
                   maxit = 50,
                   epsilon=1e-04)

temp_tune <- tune_ssl_psdh(temp_initialize, 
              seq(0.01, 0.2, 0.005),
              seq(0.4, 0.7, 0.05)
              )

optimal_scale <- temp_tune %>%
  filter(score_mean == max(temp_tune$score_mean))


mod <- fit_ssl_psdh(as.matrix(temp_x),
             as.matrix(temp_y),
                   ss=c(optimal_scale$s0, optimal_scale$s1),
                   initial_sparsity = 0.05,
                   maxit = 50,
                   epsilon=1e-04)

names(mod$coefficients)<-c("ASV", "Est") 
mod_selected <- mod$coefficients %>%
  left_join(df_key, by = "ASV")%>%
  filter(abs(Est) > 0)%>%
  select(ASV, Est, Class, Order, Family, Genus)

mod_selected
}
```

## Allo

### Genus Level

```{r}
allo_x <- df_genus %>%
  filter(study == "Allo")%>%
  select(starts_with("ASV"))

allo_y <- df_genus %>%
  filter(study == "Allo")%>%
  select(TTE, GVHD_STATUS)
```

```{r}
allo_initialize <- fit_ssl_psdh(as.matrix(allo_x),
             as.matrix(allo_y),
                   ss=c(0.01, 0.5),
                   initial_sparsity = 0.05,
                   maxit = 50,
                   epsilon=1e-04)
```

```{r}
tune_allo <- tune_ssl_psdh(allo_initialize, 
              seq(0.01, 0.2, 0.005),
              seq(0.4, 0.7, 0.05)
              )

tune_allo %>% 
  filter(score_mean == max(tune_allo$score_mean))
```

```{r}
allo_final <- fit_ssl_psdh(as.matrix(allo_x),
             as.matrix(allo_y),
                   ss=c(0.09, 0.7),
                   initial_sparsity = 0.05,
                   maxit = 50,
                   epsilon=1e-04)
```

```{r}
names(allo_final$coefficients)<-c("ASV", "Est") 
allo_selected <- allo_final$coefficients %>%
  left_join(df_genus_key, by = "ASV")%>%
  filter(abs(Est) > 0)%>%
  select(ASV, Est, Class, Order, Family, Genus)
```

### ASV Level

```{r}
allo_all <- test_run("Allo", df_asv, df_asv_key)
allo_all
```

## Liu

```{r}
liu_genus <- test_run("Liu", df_genus, df_genus_key)
liu_genus
```

```{r}
liu_all <- test_run("Liu", df_asv, df_asv_key)
liu_all
```

## Fuji

```{r}
fuji_genus <- test_run("Fuji", df_genus, df_genus_key)
fuji_genus
fuji_genus %>% View()
```

```{r}
fuji_all <- test_run("Fuji", df_asv, df_asv_key)
fuji_all
fuji_all %>% View()
```

# To do

-   Filter out low abundance features
