// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_km_censoring
Rcpp::List cpp_km_censoring(const Rcpp::NumericVector& time_, const Rcpp::NumericVector& status_);
RcppExport SEXP _bhCRR_cpp_km_censoring(SEXP time_SEXP, SEXP status_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type time_(time_SEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type status_(status_SEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_km_censoring(time_, status_));
    return rcpp_result_gen;
END_RCPP
}
// cpp_predict_risk
Rcpp::NumericMatrix cpp_predict_risk(const Rcpp::NumericMatrix& x_test_, const Rcpp::NumericMatrix& coef_);
RcppExport SEXP _bhCRR_cpp_predict_risk(SEXP x_test_SEXP, SEXP coef_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type x_test_(x_test_SEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type coef_(coef_SEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_predict_risk(x_test_, coef_));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cv_cindex
Rcpp::NumericVector cpp_cv_cindex(const Rcpp::NumericMatrix& x_test_, const Rcpp::NumericMatrix& coef_, const Rcpp::NumericVector& time_test_, const Rcpp::NumericVector& status_test_, std::string tuning, double evaluation_time, bool reverse);
RcppExport SEXP _bhCRR_cpp_cv_cindex(SEXP x_test_SEXP, SEXP coef_SEXP, SEXP time_test_SEXP, SEXP status_test_SEXP, SEXP tuningSEXP, SEXP evaluation_timeSEXP, SEXP reverseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type x_test_(x_test_SEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type coef_(coef_SEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type time_test_(time_test_SEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type status_test_(status_test_SEXP);
    Rcpp::traits::input_parameter< std::string >::type tuning(tuningSEXP);
    Rcpp::traits::input_parameter< double >::type evaluation_time(evaluation_timeSEXP);
    Rcpp::traits::input_parameter< bool >::type reverse(reverseSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cv_cindex(x_test_, coef_, time_test_, status_test_, tuning, evaluation_time, reverse));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_bhCRR_cpp_km_censoring", (DL_FUNC) &_bhCRR_cpp_km_censoring, 2},
    {"_bhCRR_cpp_predict_risk", (DL_FUNC) &_bhCRR_cpp_predict_risk, 2},
    {"_bhCRR_cpp_cv_cindex", (DL_FUNC) &_bhCRR_cpp_cv_cindex, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_bhCRR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
