# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Kaplan-Meier censoring distribution (C++ helper, for verification)
#'
#' Exposes the internal censoring-distribution estimate used by the IPCW
#' C-index so it can be checked against the R reference in
#' \code{measure_ssl_psdh()}.
#'
#' @param time Numeric vector of observed event/censoring times.
#' @param status Numeric vector of status codes (0 = censored, 1 = cause-1
#'   event, 2 = competing event).
#' @return A list with elements \code{G_Ti} = \eqn{G(T_i)} and
#'   \code{G_Ti_minus} = \eqn{G(T_i^-)}.
#' @keywords internal
cpp_km_censoring <- function(time_, status_) {
    .Call(`_bhCRR_cpp_km_censoring`, time_, status_)
}

#' Predicted risk scores X %*% beta (RcppArmadillo)
#'
#' @param x_test Numeric matrix (n_test x p) of test-fold predictors.
#' @param coef Numeric matrix (p x n_lambda) of coefficients across the
#'   lambda path, e.g. \code{fit$coef} from \code{fastcmprsk::fastCrrp()}.
#' @return Numeric matrix (n_test x n_lambda) of linear-predictor risk scores.
#' @keywords internal
cpp_predict_risk <- function(x_test_, coef_) {
    .Call(`_bhCRR_cpp_predict_risk`, x_test_, coef_)
}

#' Cross-validation C-index across a lambda path (RcppArmadillo backend)
#'
#' Computes, for each column of \code{coef} (one lambda), the test-fold
#' concordance of the risk scores \code{x_test \%*\% coef[, j]}. This is the
#' compiled kernel behind \code{cv_fastCrrp_cpp()}.
#'
#' @param x_test Numeric matrix (n_test x p) of held-out predictors.
#' @param coef Numeric matrix (p x n_lambda) of fitted coefficients along the
#'   lambda path.
#' @param time_test Numeric vector of held-out event/censoring times.
#' @param status_test Numeric vector of held-out status codes (0 = censored,
#'   1 = cause-1 event, 2 = competing event).
#' @param tuning Either \code{"normal"} (Harrell C-index, matching
#'   \code{survival::concordance}) or \code{"wolbers"} (IPCW competing-risks
#'   C-index, matching \code{measure_ssl_psdh}).
#' @param evaluation_time Numeric scalar; the time horizon used only by the
#'   \code{"wolbers"} tuning. Ignored when \code{tuning = "normal"}.
#' @param reverse Logical; orientation of the Harrell C-index for
#'   \code{tuning = "normal"}. \code{FALSE} (default) matches the
#'   \code{survival::concordance} default. Ignored when
#'   \code{tuning = "wolbers"}.
#' @return Numeric vector of length \code{ncol(coef)} of C-index values
#'   (\code{NA} where no comparable pairs exist).
#' @keywords internal
cpp_cv_cindex <- function(x_test_, coef_, time_test_, status_test_, tuning, evaluation_time, reverse = FALSE) {
    .Call(`_bhCRR_cpp_cv_cindex`, x_test_, coef_, time_test_, status_test_, tuning, evaluation_time, reverse)
}

